config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'
  resource :user
  resource :session, only: [:create, :destroy, :new]
  resources :subs
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
  end
  resources :comments, only: [:create, :show]

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  user_id    :integer
#  post_id    :integer
#  parent_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base

  belongs_to :author, class_name: 'User', foreign_key: :user_id, primary_key: :id
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', foreign_key: :parent_id, primary_key: :id
  has_many :children, class_name: 'Comment', foreign_key: :parent_id, primary_key: :id
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, presence: true
  # belongs_to :sub
  belongs_to(:author, class_name: "User", foreign_key: :user_id, primary_key: :id)
  has_many :subs, through: :post_subs
  has_many :post_subs
  has_many :comments, dependent: :destroy

  def author_email
    author.email
  end

end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  sub_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  belongs_to :post
  belongs_to :sub
  
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, presence: true
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  has_many :post_subs
  has_many :posts, through: :post_subs


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: { message: "Password can't be blank" }
  after_initialize :ensure_session_token
  has_many :subs, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy


  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    if user.nil?
      nil
    else
      (BCrypt::Password.new(user.password_digest).is_password?(password)) ? user : nil
    end
  end

  attr_reader :password
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  private

    def ensure_session_token
      self.session_token ||= SecureRandom::urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :ensure_logged_in
  helper_method :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:session_token]
      @current_user ||= User.find_by_session_token(session[:session_token])
    else
      nil
    end
  end

  def log_in! user
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def ensure_logged_in
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @post_id = params[:post_id]
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end


  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in
  before_action :ensure_author, only: :update

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.sub_ids = params[:post][:sub_ids]
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.where(parent_id: nil)
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
  end

  def update
    @post = Post.find(params[:id])
    @post.sub_ids = params[:post][:sub_ids]
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :url, :sub_ids)
    end

    def ensure_author
      post = Post.find(params[:id])
      redirect_to post_url(post) if current_user != post.author
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_logged_in, only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      log_in! @user
      redirect_to user_url
    else
      @user = User.new(email: params[:user][:email])
      render :new
    end
  end


  def destroy
    log_out!
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_logged_in, except: :index
  before_action :ensure_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user

    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def ensure_moderator
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless current_user == @sub.moderator
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, only: :show

  def create
    @user = User.new(user_params)
    if @user.save!
      redirect_to user_url
      log_in! @user
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Create a new comment</h1>

<form action="<%= comments_url %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
<input type="hidden" name="comment[post_id]" value="<%= @post_id %>">

<textarea name="comment[content]" rows="8" cols="40"></textarea>

<input type="submit" value="Submit Comment">
</form>

app/views/comments/show.html.erb
<%= render partial: "shared/comment", locals: { comment: @comment } %>

<form action="/comments" method="post">
  <input type="_hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <textarea name="comment[parent]" rows="8" cols="40"></textarea>
  <input type="submit" value="Reply to comment">
</form>


<%= link_to "Back to #{@comment.post.title}", post_url(@comment.post) %><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "All Subs", subs_url %><br><br>
<% if current_user %>
  <%= link_to "Profile", user_url %>
  <br><br><%= button_to "Logout", session_url, method: :delete %>
<% else %>
  <%= link_to "Login", new_session_url %> or <%= link_to "Sign Up", new_user_url %>
<% end %>
<br><br>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit '<%= @post.title %>'</h1>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  Title: <input type="text" name="post[title]" value="<%= @post.title %>">
  <br>Sub:<br>
    <% @subs.each do |sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
        <%= 'checked' if @post.sub_ids.include?(sub.id) %>> <%= sub.title %><br>
    <% end %>
  Content: <textarea name="post[content]"><%= @post.content %></textarea>
  Link: <input type="text" name="post[url]" value="<%= @post.url %>">
  <input type="submit" value="Update Post">
</form>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Title: <input type="text" name="post[title]" value="<%= @post.title %>">
  <br>Sub:<br>
  <% @subs.each do |sub| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"> <%= sub.title %><br>
  <% end %>
  Content: <textarea name="post[content]"><%= @post.content %></textarea>
  Link: <input type="text" name="post[url]" value="<%= @post.url %>">
  <input type="submit" value="Add Post">
</form>

app/views/posts/show.html.erb
<%= render "/shared/post", post: @post %>
<h2>Comments</h2>
<%= render partial: 'shared/comment', collection: @comments %>
<%= link_to 'Comment on this post', new_post_comment_url(@post) %>
<h2>Posted On</h2>
<% @post.subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub)%>
<% end %>

app/views/shared/_comment.html.erb
<% if current_user == comment.author %>
  <b><%= link_to "Comment on #{comment.post.title}", comment_url(comment) %></b><br>
<% else %>
  <b><%= link_to "Comment by #{comment.author.email}", comment_url(comment) %></b><br>
<% end %>

<%= comment.content %><br>

app/views/shared/_post.html.erb
<b><%= link_to "#{post.title}", post_url(post) %></b>
<% if post.author == @current_user %>
 (<%= link_to "Edit Post", edit_post_url(post) %>)
 <% else %>
 <%= post.author_email %>
<% end %>

<% if post.url.length > 0 %>
  <br> <a href="<%= post.url %>"><%= post.url %></a>
<% end %>

<br> <%= post.content %>
<br><br>

app/views/subs/_sub.html.erb
<b><%= link_to sub.title, sub_url(sub) %></b>
<br>
<%= sub.description %>
<br><br>

app/views/subs/edit.html.erb
<h3>Edit <%= @sub.title %>!</h3>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  Title: <input type="text" name="sub[title]" value="<%= @sub.title %>">
  Description: <input type="text" name="sub[description]" value="<%= @sub.description %>">
  <input type="submit" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h3> All subs </h3>

<%= render @subs %>

<%= link_to "Create a new sub", new_sub_url %>
<br><%= link_to 'Create a post', new_post_url %>

app/views/subs/new.html.erb
<h3>Create a new sub!</h3>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  Title: <input type="text" name="sub[title]" value="<%= @sub.title %>">
  Description: <input type="text" name="sub[description]" value="<%= @sub.description %>">
  <input type="submit" value="Create Sub!">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<%= @sub.description %>
<br><br>
<%= render partial: "shared/post", collection: @posts %>
<br><br>
<%= link_to 'Edit Sub', edit_sub_url(@sub) %><br>

<%= link_to 'Create a post', new_post_url %>

app/views/users/new.html.erb
<h3>Sign Up!</h3>

<form action="<%= user_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Email: <input type="text" name="user[email]" value="<%= @user.email %>">
  Password: <input type="password" name="user[password]" value="">
  <input type="submit" value="Sign up!">
</form>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<h2>Your Posts</h2>
<%= render partial: "shared/post", collection: @user.posts %>

<h2>Your Comments</h2>
<%= render partial: "shared/comment", collection: @user.comments %>